import { Task, DailyProgress, SubjectProgress } from '@/types/task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete Calculus Assignment',
    description: 'Solve problems from Chapter 5',
    subject: 'Mathematics',
    priority: 'high',
    status: 'in-progress',
    dueDate: '2026-01-24',
    estimatedHours: 3,
    completedHours: 1.5,
    dependencies: [],
    createdAt: '2026-01-20',
  },
  {
    id: '2',
    title: 'Read Physics Chapter 8',
    description: 'Study thermodynamics concepts',
    subject: 'Physics',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-01-25',
    estimatedHours: 2,
    completedHours: 0,
    dependencies: [],
    createdAt: '2026-01-20',
  },
  {
    id: '3',
    title: 'Physics Lab Report',
    description: 'Write up experiment results',
    subject: 'Physics',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-01-26',
    estimatedHours: 4,
    completedHours: 0,
    dependencies: ['2'],
    createdAt: '2026-01-20',
  },
  {
    id: '4',
    title: 'History Essay Draft',
    description: 'First draft of World War II essay',
    subject: 'History',
    priority: 'medium',
    status: 'completed',
    dueDate: '2026-01-22',
    estimatedHours: 5,
    completedHours: 5,
    dependencies: [],
    createdAt: '2026-01-18',
  },
  {
    id: '5',
    title: 'Chemistry Problem Set',
    description: 'Complete organic chemistry problems',
    subject: 'Chemistry',
    priority: 'low',
    status: 'pending',
    dueDate: '2026-01-27',
    estimatedHours: 2,
    completedHours: 0,
    dependencies: [],
    createdAt: '2026-01-21',
  },
  {
    id: '6',
    title: 'Literature Analysis',
    description: 'Analyze themes in Shakespeare',
    subject: 'Literature',
    priority: 'medium',
    status: 'completed',
    dueDate: '2026-01-21',
    estimatedHours: 3,
    completedHours: 3,
    dependencies: [],
    createdAt: '2026-01-19',
  },
];

export const weeklyProgress: DailyProgress[] = [
  { date: 'Mon', completedTasks: 3, totalTasks: 5, hoursStudied: 4.5 },
  { date: 'Tue', completedTasks: 2, totalTasks: 4, hoursStudied: 3 },
  { date: 'Wed', completedTasks: 4, totalTasks: 6, hoursStudied: 5.5 },
  { date: 'Thu', completedTasks: 1, totalTasks: 3, hoursStudied: 2 },
  { date: 'Fri', completedTasks: 3, totalTasks: 4, hoursStudied: 4 },
  { date: 'Sat', completedTasks: 2, totalTasks: 2, hoursStudied: 3 },
  { date: 'Sun', completedTasks: 1, totalTasks: 3, hoursStudied: 1.5 },
];

export const subjectProgress: SubjectProgress[] = [
  { subject: 'Mathematics', completed: 5, pending: 2, inProgress: 1 },
  { subject: 'Physics', completed: 3, pending: 2, inProgress: 0 },
  { subject: 'Chemistry', completed: 4, pending: 1, inProgress: 0 },
  { subject: 'History', completed: 6, pending: 0, inProgress: 0 },
  { subject: 'Literature', completed: 4, pending: 1, inProgress: 1 },
];

export const subjects = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'History',
  'Literature',
  'Computer Science',
  'Biology',
  'Economics',
];
